# Generated by Django 3.1.1 on 2020-11-13 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageChampion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main', models.CharField(default=None, max_length=200, null=True)),
                ('splash_art', models.CharField(default=None, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageSpell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passive', models.CharField(default=None, max_length=200)),
                ('q', models.CharField(default=None, max_length=200)),
                ('w', models.CharField(default=None, max_length=200)),
                ('e', models.CharField(default=None, max_length=200)),
                ('r', models.CharField(default=None, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ImageSummonnerSpell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default=None, max_length=200)),
                ('description', models.TextField(default=None, max_length=200)),
                ('img', models.CharField(default=None, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='KeyStone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rune', models.CharField(default=None, max_length=200, null=True)),
                ('name', models.CharField(default=None, max_length=200, null=True)),
                ('img', models.CharField(default=None, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rune',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=200)),
                ('img', models.CharField(default=None, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SubRune',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rune', models.CharField(default=None, max_length=200, null=True)),
                ('row', models.IntegerField(default=None, null=True)),
                ('name', models.CharField(default=None, max_length=200, null=True)),
                ('img', models.CharField(default=None, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SummonnerSpell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('img', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noxusProject.imagesummonnerspell')),
            ],
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passive', models.CharField(default=None, max_length=200)),
                ('q', models.CharField(default=None, max_length=200)),
                ('w', models.CharField(default=None, max_length=200)),
                ('e', models.CharField(default=None, max_length=200)),
                ('r', models.CharField(default=None, max_length=200)),
                ('img', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noxusProject.imagespell')),
            ],
        ),
        migrations.CreateModel(
            name='RuneChampion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=200)),
                ('key_stone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main', to='noxusProject.keystone')),
                ('row1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='row1', to='noxusProject.subrune')),
                ('row2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='row2', to='noxusProject.subrune')),
                ('row3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='row3', to='noxusProject.subrune')),
                ('rune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main', to='noxusProject.rune')),
                ('sub_row1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_row1', to='noxusProject.subrune')),
                ('sub_row2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_row2', to='noxusProject.subrune')),
                ('sub_rune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub', to='noxusProject.rune')),
            ],
        ),
        migrations.CreateModel(
            name='ItemChampion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('items_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item1', to='noxusProject.items')),
                ('items_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item2', to='noxusProject.items')),
                ('items_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item3', to='noxusProject.items')),
                ('items_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item4', to='noxusProject.items')),
                ('items_5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item5', to='noxusProject.items')),
                ('items_6', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item6', to='noxusProject.items')),
                ('starter1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starter1', to='noxusProject.items')),
                ('starter2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starter2', to='noxusProject.items')),
            ],
        ),
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('title', models.CharField(default=None, max_length=200, null=True)),
                ('top', models.BooleanField(default=False)),
                ('mid', models.BooleanField(default=False)),
                ('jungler', models.BooleanField(default=False)),
                ('adc', models.BooleanField(default=False)),
                ('support', models.BooleanField(default=False)),
                ('img', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='noxusProject.imagechampion')),
                ('spell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noxusProject.spell')),
            ],
        ),
    ]
