# Generated by Django 3.1.2 on 2020-11-15 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noxusProject', '0002_auto_20201115_2040'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummonnerSpellChampion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('spell1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spell1', to='noxusProject.summonnerspell')),
                ('spell2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spell2', to='noxusProject.summonnerspell')),
            ],
        ),
    ]
