# Generated by Django 3.1.2 on 2020-11-22 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('noxusProject', '0003_summonnerspellchampion'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBuild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build_name', models.CharField(max_length=200)),
                ('champion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='noxusProject.champion')),
                ('items_1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_item1', to='noxusProject.items')),
                ('items_2', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_item2', to='noxusProject.items')),
                ('items_3', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_item3', to='noxusProject.items')),
                ('items_4', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_item4', to='noxusProject.items')),
                ('items_5', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_item5', to='noxusProject.items')),
                ('items_6', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_item6', to='noxusProject.items')),
                ('key_stone', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_main', to='noxusProject.keystone')),
                ('row1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_row1', to='noxusProject.subrune')),
                ('row2', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_row2', to='noxusProject.subrune')),
                ('row3', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_row3', to='noxusProject.subrune')),
                ('starter1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_starter1', to='noxusProject.items')),
                ('starter2', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_starter2', to='noxusProject.items')),
                ('sub_row1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_sub_row1', to='noxusProject.subrune')),
                ('sub_row2', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_sub_row2', to='noxusProject.subrune')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
